yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    """Модель для хранения постов."""
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Текст нового поста',
                            max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey('Group',
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True,
                              related_name='posts',
                              verbose_name='Группа',
                              help_text='Группа, к которой будет относиться '
                              'пост'
                              )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date', ]

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    """Модель для хранения групп."""
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Модель для хранения комментариев."""
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments'
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments'
                               )
    text = models.TextField(max_length=200,
                            verbose_name='Текст',
                            help_text='Текст нового комментария')
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    """Модель для хранения подписок."""
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='user_author_unique')
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """
    Форма для добавления постов.
    """
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """
    Форма для добавления комментариев.
    """
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .helpers import paginate


def index(request):
    """
    Функция для отображения главной страницы index.
    """
    posts = Post.objects.all()
    page_obj = paginate(request, posts)
    context = {
        'page_obj': page_obj,
        'show_link': True,
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    """
    Функция для отображения для вывода списка всех групп.
    """
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginate(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """
    Функция для отображения профиля пользователя.
    """
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    template = 'posts/profile.html'
    page_obj = paginate(request, posts)
    posts_count = posts.count()
    is_auth = request.user.is_authenticated
    is_exist = Follow.objects.filter(user=request.user.id,
                                     author=author).exists()
    following = is_auth and is_exist

    context = {
        'page_obj': page_obj,
        'author': author,
        'posts_count': posts_count,
        'show_link': False,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """
    Функция для отображения страницы поста.
    """
    post = get_object_or_404(Post, pk=post_id)
    posts_count = post.author.posts.count()
    comments = post.comments.all()
    comment_form = CommentForm()
    context = {
        'post': post,
        'posts_count': posts_count,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """
    Функция для создания поста.
    """
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """
    Функция для редактирования поста.
    """
    post = get_object_or_404(Post, id=post_id)

    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post.id)

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)

    is_edit = True
    context = {
        'form': form,
        'post': post,
        'is_edit': is_edit
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """
    Функция для добавления комментария.
    """
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post.id)


@login_required
def follow_index(request):
    """
    Функция для отображения всех подписок пользователя.
    """
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate(request, posts)
    context = {
        'page_obj': page_obj,
        'show_link': True,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """
    Функция для подпики на автора.
    """
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author
        )
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    """
    Функция для того, чтобы отписаться от автора.
    """
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    if follow.exists():
        follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %}
{% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %}
{% endblock %}

{% block content %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                Редактировать пост
                {% else %}
                Новый пост
                {% endif %}
              </div>
              <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}

                  {# Выводим поля в цикле, по отдельности #}
                  {% for field in form %}
                    <div class="form-group row my-3">
                      <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                          {% if field.field.required %}
                            <span class="required text-danger">*</span>
                          {% endif %}
                      </label>
                      {# К полю ввода добавляем атрибут class #}
                      {{ field|addclass:'form-control' }}
                        {% if field.help_text %}
                          <small
                             id="{{ field.id_for_label }}-help"
                             class="form-text text-muted"
                          >
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}
                    </div>
                  {% endfor %}
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Мои подписки
{% endblock %}


{% block content %}
  <h1>Мои подписки</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  <div class="col-md-12 my-4 shadow-sm">
    <div class="card">
      <div class="card-body">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {% include 'includes/article.html' %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          <hr>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{{ group.title }}
{% endblock %}


{% block content %}
  <h1>{{ group.title }}</h1>
  <p> {{group.description }} </p>
  {% for post in page_obj %}
  <div class="col-md-12 my-4 shadow-sm">
    <div class="card">
      <div class="card-body">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {% include 'includes/article.html' %}
      </div>
    </div>
  </div>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}
  Последние обновления на сайте
{% endblock %}


{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% include 'posts/includes/switcher.html' %}
  {% cache 20 index_page page_obj.number %}
  {% for post in page_obj %}
  <div class="col-md-12 my-4 shadow-sm">
    <div class="card">
      <div class="card-body">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {% include 'includes/article.html' %}
        {% if post.group %}
          <a class="text-shadow" href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Пост {{ post|truncatechars:30 }}
{% endblock %}
{% load thumbnail %}

    {% block content %}
        <div class="row">
          <aside class="col-12 col-md-3 border rounded shadow-sm">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-shadow">
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
              {% if post.group %}
              <li class="list-group-item text-shadow">
                Группа: {{ post.group.title }}
                <br>
                {% if post.group %}
                <a class="text-shadow" href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
                {% endif %}
              {% endif %}
              </li>
              <li class="list-group-item text-shadow">
                Автор:
                  <a href="{% url 'posts:profile' post.author.username %}">
                  {{ post.author.get_full_name }}
                  </a>
                  {{ user.username }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center text-shadow">
                Всего постов автора:  <span >{{ posts_count }}</span>
              </li>
              <li class="list-group-item text-shadow">
                <a href="{% url "posts:profile" post.author %}">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            {% thumbnail post.image "1400x800" crop="center" upscale=True as im %}
              <img class="card-img my-2 rounded shadow-sm" src="{{ im.url }}">
            {% endthumbnail %}
            <p class="text-shadow">
            {{ post.text }}
            </p>
            <a href="{% url 'posts:post_edit' post.pk %}">
              {% if post.author == user %}
                <button type="submit" class="btn btn-primary">
                  редактировать запись
                </button>
              {% endif %}
            </a>
            <a href="#">
              {% if post.author == user %}
                <button type="submit" class="btn btn-danger">
                  удалить запись
                </button>
              {% endif %}
            </a>
            {% include 'posts/includes/comments.html' %}
          </article>
        </div>
    {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{{ author.get_full_name }} профайл пользователя
{% endblock %}


    {% block content %}
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ posts_count }} </h3>
      {% if request.user != author %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
        {% for post in page_obj %}
        <div class="col-md-12 my-4 shadow-sm">
          <div class="card">
            <div class="card-body">
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
            {% include 'includes/article.html' %}
              {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              <hr>
            {% endif %}
            </div>
          </div>
        </div>
        {% endfor %}
        </article>
        {% include 'posts/includes/paginator.html' %}
      </div>
    {% endblock %}